spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/auth_service_db
    username: codingninjas
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
